### PR TITLE
Update Kotlin style to look more similar to Java (feedback from #148)

### PR DESCRIPTION
**Pull request by simba909**
## Description

After seeing the open issue about making Kotlin syntax look more like Java (#148), I decided to see if I can pitch in and help with the efforts :)

This PR doesn't do much, it basically just reverts a few Kotlin style properties in both the light and dark theme to the "Inherit from Java" settings. However I believe the difference might still be welcome if you work with both languages on a regular basis :) This affects:

 - Visibility modifiers
 - Line comments
 - Method parameters
 - Number literals

Let me know if there's a better way to do this!

### Before
screen shot 2017-06-29 at 18 04 31

### After
screen shot 2017-06-29 at 18 37 15

### Before
screen shot 2017-06-29 at 18 02 59

### After
screen shot 2017-06-29 at 17 35 06

### CODE REVIEW

**Comment by jkaving** [comment]
Sorry about responding so late, and thanks for putting in the effort.
This pull request is really nicely described (with screen shots and all!)

I just tried taking this a bit further, by checking "Use inherited attributes" for all Kotlin colors where it is available.
To me this seems to make it even closer to the Java color scheme.

Is there a reason why you limited this to only a few settings?

**Comment by simba909** [comment]
There's no real reason for it, just that I personally like the fact that the Kotlin code still looks slightly different from Java. Kotlin and Java are very much similar, but still have some important differences and I thought this would make them more similar but at the same time keep the "uniqueness" of the Kotlin highlighting :)

With that said I can agree that making it look more similar to Java might be even better for the project as a whole. If I really want to I can still change the values locally :)

**Comment by soshial** [comment]
Azaming work! Maybe, making them look even more similar would be logical.

**Comment by simba909** [comment]
If there are any changes that I should apply before merging, I'll gladly fix them :)

**Comment by soshial** [comment]
Any progress on this?

**Comment by soshial** [comment]
How can we fix code inspections to look similar. Now it looks like this:
screen shot 2018-10-31 at 23 54 34

**Comment by simba909** [comment]
@soshial After some fiddling I've now updated the `settings.jar` file with my changes. Thanks for pointing it out! I also took the time to merge the changes from the master branch and remove some color scheme duplications inside the jar file.

I couldn't find a way to alter the dotted underline of some Kotlin warnings though; unsure if it's controllable through the color scheme (or I just couldn't find the setting) 🤔

**Comment by jkaving** [comment]
The `settings.jar` file isn't really supposed to be fiddled with.
The idea is that after doing changes to the color scheme files you just run the `buildjar.sh` script to generate a new `settings.jar`.
It will then contain all the necessary files.

The redundant files in the generated `settings.jar` are XML files that are kept for backwards-compatibility.

Thanks fo the effort though.
Instead of asking you to update the `settings.jar` file again I have now simply cherry-picked your first commit (the one containing the changes to the color scheme). The new commit (which is now in `master`) with your changes is 33ff5ded0be12635461c1ca1440d3eaffef6ebbd.

**Pull request closed without merging**
