### PR TITLE
Fix constructor in Kotlin

### PR DESCRIPTION
**Pull request by soshial**
Constructors should NOT be italic. In other themes they inherit from "Identifiers -> Function calls".

Compare with Intellij Light and Intellij Dark (see 3rd line: `val ints = java.util.ArrayList<Int?>(2)`):

Screenshot 2023-10-30 at 8 46 46

Screenshot 2023-10-30 at 8 53 27

Solarized Light, BEFORE:

Screenshot 2023-10-30 at 8 44 59

Solarized Light, AFTER:

Screenshot 2023-10-30 at 8 46 11

Solarized Dark, BEFORE:

Screenshot 2023-10-30 at 8 52 26

Solarized Dark, AFTER:

Screenshot 2023-10-30 at 8 52 38

### CODE REVIEW

**Comment by soshial** [comment]
@jkaving , please have a look at this.

**Comment by soshial** [comment]
Do you mind having a look at this bugfix, @jkaving?

**Comment by jkaving** [comment]
@soshial - Sorry about not merging this earlier.

Thanks for the fix - and the work you put in creating the PR 👍

**Comment by jkaving** [comment]
See the beginning of [my comment here](https://github.com/jkaving/intellij-colors-solarized/issues/180#issuecomment-1251226549) for a bit of an explanation for why I've not been very active in updating this color scheme.

**Comment by soshial** [comment]
Thanks a lot, @jkaving, for resolving all the issues stacked up during last years. Appreciate it!

**Comment by jkaving** [comment]
> Thanks a lot, @jkaving, for resolving all the issues stacked up during last years. Appreciate it!

Thanks @soshial for nagging me about it!

I've felt bad about ignoring this repo for _years_.
So it felt really good to be able to fix quite a lot yesterday (even if it meant that I got a bit less sleep than ideal last night 🙂).

**Pull request merged**
