### PR TITLE
Add JavaScript class color

### PR DESCRIPTION
**Pull request by NicolasSiver**
Looks like latest versions of WebStorm is introduced a new property for JS classes.
Change is small. I don't have JDK to compile a .jar file.

### CODE REVIEW

**Comment by aik099** [comment]
Please also:

1. include built JAR file that can be imported in IDE
2. attach screenshot showing difference in color from old to new with affected element highlighted

**Comment by NicolasSiver** [comment]
### Before

screen shot 2016-11-08 at 10 09 21 pm

### After

screen shot 2016-11-08 at 10 10 05 pm

**Comment by jkaving** [comment]
Thanks for contributing this fix.
However, I don't see this problem in IntelliJ IDEA and not in WebStorm either (I downloaded and installed 2016.3).

The JavaScript Class is set to inherit its color from Language defaults:
screenshot_of_webstorm

... and in Language defaults it is set to inherit the default color from identifiers:
screenshot_of_webstorm

I think it is a good idea to let as many colors as possible be defined in Language defaults and override as few colors as possible in the settings for different languages.

I wonder why you have the black color without your change.
Could you have done other changes to your color scheme that causes this?

**Comment by NicolasSiver** [comment]
I have found several differences. I have a custom `Solarized Dark` which is technically merged with my profile. My profile is very old, as I can see It has black in Language Defaults. I'm going to solve it by merging latest Solarized Dark.

The second difference, that I'm using `yellow` for class names. I have found It's more idiomatic.

Most of the time, when I'm making a change, I'm trying to find a reference here - http://ethanschoonover.com/solarized

**Comment by NicolasSiver** [comment]
Main difference was this:

```
<option name="DEFAULT_IDENTIFIER">
  <value>
    <option name="FOREGROUND" value="839496" />
  </value>
</option>
```

I didn't have it, thus 000000 was used as a default color.

And the main difference for the JavaScript is this, I'm considering to contribute it:

```
    <option name="JS.BRACES">
      <value>
        <option name="FOREGROUND" value="268bd2" />
      </value>
    </option>
    <option name="JS.BRACKETS">
      <value>
        <option name="FOREGROUND" value="268bd2" />
      </value>
    </option>
    <option name="JS.CLASS">
      <value>
        <option name="FOREGROUND" value="b58900" />
      </value>
    </option>
```

**Pull request closed without merging**
